#!/usr/bin/env sh

# SIP-friendly starter config. Scripting additions are intentionally disabled.

# global settings
yabai -m config                                 \
    layout                       bsp            \
    window_placement             second_child   \
    window_insertion_point       focused        \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_zoom_persist          on             \
    window_shadow                off            \
    window_opacity               off            \
    window_animation_duration    0.0            \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   0              \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "yabai configuration loaded.."
